resources:
  - name: connecting_resource_node_test_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: node_test_run
    steps:
      - name: myStep112
        type: Bash
        configuration:
          outputResources:
            - name: connecting_resource_node_test_1
#               trigger: false
          integrations:
            - name: vijay
        execution:
          onExecute:
            - write_output connecting_resource_node_test_1 "test=value"

      - name: c7dynamic
        type: Bash
        configuration:
          nodePool: c7dynamic
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                autoPull: false
                registry: DockerRegistry       
          inputResources:
            - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - docker images
            - docker buildx

      - name: u18dynamic
        type: Bash
        configuration:
          nodePool: u18dynamic
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                autoPull: false
                registry: DockerRegistry              
          inputResources:
            - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - docker images
            - docker buildx

      - name: u20dynamic
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                autoPull: false
                registry: DockerRegistry           
          nodePool: u20dynamic
          inputResources:
            - name: connecting_resource_node_test_1
        execution:
          onExecute:
            - docker images
            - docker buildx

      # - name: c8dynamic
      #   type: Bash
      #   configuration:
      #     nodePool: c8dynamic
      #     inputResources:
      #       - name: connecting_resource_node_test_1
      #   execution:
      #     onExecute:
      #       - printenv
      #       - docker images

#       - name: win_2019
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           inputResources:
#             - name: connecting_resource_node_test_1
#         execution:
#           onExecute:
#             - write-output "Hi"
#             - docker images
