resources:
  - name: connecting_resource_node_test_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/nodeTest     

pipelines:
  - name: node_test_run
    steps:
      - name: myStep
        type: Bash
        configuration:
          outputResources:
            - name: connecting_resource_node_test_1
#               trigger: false
          integrations:
            - name: vijay
        execution:
          onExecute:
            - write_output connecting_resource_node_test_1 "test=value"

      - name: c7dynamic
        type: Bash
        configuration:     
          nodePool: pipelines_c7
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                registry: dockerDotJfrog       
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
          integrations:
            - name: vijay_docker
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath
            - docker images
            - docker buildx
            - docker buildx build  --platform linux/amd64 -t vijaydocker1991/centos7 --push .

      - name: u18dynamic
        type: Bash
        configuration:
          nodePool: pipelines_u18
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                registry: dockerDotJfrog              
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
          integrations:
            - name: vijay_docker            
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath          
            - docker images
            - docker buildx
            - docker buildx build  --platform linux/amd64 -t vijaydocker1991/ubuntu18t --push .

      - name: u20dynamic
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-c7
                tag: 0.0.0-f11020
                registry: dockerDotJfrog           
          nodePool: pipelines_u20
          inputResources:
            - name: test_1234
            - name: connecting_resource_node_test_1
          integrations:
            - name: vijay_docker            
        execution:
          onExecute:
            - pushd $res_test_1234_resourcePath          
            - docker images
            - docker buildx
            - docker buildx build  --platform linux/amd64 -t vijaydocker1991/ubuntu20 --push .

#       - name: win_2019
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           inputResources:
#             - name: connecting_resource_node_test_1
#         execution:
#           onExecute:
#             - write-output "Hi"
#             - docker images
